# Generated by Django 2.2 on 2019-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industrial_Logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambient', models.FloatField()),
                ('coolant', models.FloatField()),
                ('u_d', models.FloatField()),
                ('u_q', models.FloatField()),
                ('motor_speed', models.FloatField()),
                ('torque', models.FloatField()),
                ('i_d', models.FloatField()),
                ('i_q', models.FloatField()),
                ('pm', models.FloatField()),
                ('stator_yoke', models.FloatField()),
                ('stator_tooth', models.FloatField()),
                ('stator_winding', models.FloatField()),
                ('profile_id', models.IntegerField()),
            ],
            options={
                'db_table': 'gydb',
            },
        ),
        migrations.CreateModel(
            name='hjdb',
            fields=[
                ('idc', models.AutoField(db_column='Idc', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('temperature', models.IntegerField(blank=True, db_column='Temperature', null=True)),
                ('humidity', models.IntegerField(blank=True, db_column='Humidity', null=True)),
            ],
            options={
                'db_table': 'hjdb',
            },
        ),
    ]
