# Generated by Django 2.2.5 on 2019-12-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Industrial_Logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devtem',
            options={},
        ),
    ]
