# Generated by Django 3.1.3 on 2020-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industrial_Logs', '0002_bme280sof_deviceinfo_devtem_gydb_hjdb_temhum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sds011Sof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('p1', models.FloatField(blank=True, db_column='P1', null=True)),
                ('p2', models.FloatField(blank=True, db_column='P2', null=True)),
            ],
            options={
                'db_table': 'sds011sof',
                'managed': False,
            },
        ),
    ]
